Development
sumaerjolly/enumerable pull request #2
Opened 2019-06-14 16:10 UTC by sumaerjolly

2019-06-14 18:13 UTC, AdnanAfsari requested changes
**Hello @sumaerjolly @em-em-D Great Work :)**

You are almost there but you have to add few more things 

- You have to write test for every methods, you missed few of them and every methods should have 2 3 test case.

- The project should have  a descriptive README.md.

Please complete those  and submit for another review

Happy coding :)

2019-06-17 15:08 UTC, mcrd25 requested changes
# Good job with tests! 😄 

**I'd like for you to address my review comments. In particular, I'd like for you to address:**
- my_each
- my_each_with_index
- my_count
**Please also consider my other comments**

**Another thing I'd like for you to address is that your test variables are hard coded which does not give much variety... try randomizing your tests a bit. Here is a good example... this test changes test input on each run and gives you a better idea that your methods work with different values.**

```ruby
ARRAY_SIZE = 100
LOWEST_VALUE = 0
HIGHEST_VALUE = 9

let(:array) { Array.new(ARRAY_SIZE) { rand(LOWEST_VALUE...HIGHEST_VALUE) } }
  let(:block) { proc { |num| num < (LOWEST_VALUE + HIGHEST_VALUE) / 2 } }

  describe 'my_each' do
    it 'calls the given block once for each element in self' do
      my_each_output = ''
      block = proc { |num| my_each_output += num.to_s }
      array.each(&block)
      each_output = my_each_output.dup
      my_each_output = ''
      array.my_each(&block)
      expect(my_each_output).to eq(each_output)
    end
  end

  describe 'my_each_with_index' do
    it 'calls the given block once for each element in self' do
      my_each_output = ''
      block = proc { |num, idx| my_each_output += "Num: #{num}, idx: #{idx}\n" }
      array.each_with_index(&block)
      each_output = my_each_output.dup
      my_each_output = ''
      array.my_each_with_index(&block)
      expect(my_each_output).to eq(each_output)
    end
  end

  describe 'my_select' do
    it 'returns an array containing all elements of enum for which the given block returns a true value' do
      expect(array.my_select(&block)).to eq(array.select(&block))
    end
  end
```

**You have done a really good job so far! I know your previous reviewer requested only that you add the other tests but I'd really like you to improve your testing in general and have your test do what they are described as doing!  We are almost ready for 🚀**


***If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media.***

**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/)

2019-06-17 15:08 UTC, mcrd25 commented on README.md
> +In this method we recreated some of the methods in the enumerable model. After creating it we used Rspec to verify whether our methods are correct
Try adding Github username and links to all contributors
Try adding a title
Try structuring it a bit better using basic Markdown. You can get a cheatsheet [here](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet).

2019-06-17 15:08 UTC, mcrd25 commented on spec/enumerable_spec.rb
> +        it "Iterates through each element of an array" do
Your description of the test does not match what the test is testing.
This it block actually tests that it returns self, basically all three of your tests whether you change the block passed or not would return self.  So maybe one test like this is fine. What if no block is passed?

If you want to test that it iterates through array etc you may have to do a test like the following:

```ruby
it 'calls the given block once for each element in self' do
      my_each_output = ''
      block = proc { |num| my_each_output += num.to_s }
      array.each(&block)
      each_output = my_each_output.dup
      my_each_output = ''
      array.my_each(&block)
      expect(my_each_output).to eq(each_output)
    end
```
Here are some more ideas:
```ruby
it 'returns original array when no output' do
  expect(test_arr.my_each { test_block }).to eq(test_arr)
end

it 'prints result to stdout from block calculation i * 2' do
  expect { test_arr.my_each { |i| print i * 2 } }.to output(/246/).to_stdout
end
```
These are only ideas of course do not replicate it exactly

2019-06-17 15:08 UTC, mcrd25 commented on spec/enumerable_spec.rb
> +        it "iterates through the array when you pass a block also" do
Technically you've tested this already. The previous tests you did pass a block

2019-06-17 15:08 UTC, mcrd25 commented on spec/enumerable_spec.rb
> +        it "passes the index of each element of an array" do
Same issues as with my_each. 

Try comparing this to original each_With_index_method. You may even do negative tests like if your method does not handle when the block is not given, you expect it to raise an error when the block is not given and not to raise an error when the block is given.


Try to be creative =)

2019-06-17 15:08 UTC, mcrd25 commented on spec/enumerable_spec.rb
> +    describe "#my_select" do
Your my_select tests are fine. 

Another thing you can do is test to against official enumera le method like 
```ruby
it 'all above-mentioned tests match the official enumerable method counterpart' do
  expect(test_arr.my_select(&:even?)).to eq(test_arr.select(&:even?))
  expect(test_arr.my_select.is_a?(Enumerator)).to eq(test_arr.select.is_a?(Enumerator))
end
```

2019-06-17 15:08 UTC, mcrd25 commented on spec/enumerable_spec.rb
> +    describe "#my_all?" do
These tests are fine also. But try to consider being more creative and maybe testing against original method

2019-06-17 15:08 UTC, mcrd25 commented on spec/enumerable_spec.rb
> +    describe "#my_any?" do
This is fine also

2019-06-17 15:08 UTC, mcrd25 commented on spec/enumerable_spec.rb
> +    describe "#my_map" do
this is fine

2019-06-17 15:08 UTC, mcrd25 commented on spec/enumerable_spec.rb
> +        it "returns the total number of elements in an array" do
Every single one of your test structure is 4 in length. Try mixing it up a little. This does not really tell me your method works. What if your method could only count up to 4? Not that it does but you get what I'm saying?

2019-06-19 19:50 UTC, JamesOkunlade approved these changes
### Good to go guys!!!
 
You have implemented the three tests my_each, my_each_with_index, and my_count as requested by the previous reviewer. 

This project meets the basic requirements however, you should learn to employ the method of best practices the last reviewer as recommended. 

Go ahead and merge to master, close pull request and fill the project completion form for this project.

Good luck with your future projects. :+1::+1:

2019-06-20 06:27 UTC, merged